### ISSUE TITLE
Docs: steps to clone 2nic and 3nic example reference 1nic

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/terraform-azure-bigip-module#1]
Docs need updating for the 2nic and 3nic example.

Both the 2nic and 3nic example have the following in the README doc. Notice, it references the 'bigip_azure_1nic_deploy' folder instead of the correct 2nic or 3nic folder.

Steps to clone and use the provisioner locally
$ git clone https://github.com/f5devcentral/terraform-azure-bigip-module
$ cd terraform-azure-bigip-module/examples/bigip_azure_1nic_deploy

**Comment by nmenant** [comment]
Thanks Jeff, we'll look into fixing this. TER-442 has been created to address this

**Comment by nmenant** [comment]
this is fixed now
