### ISSUE TITLE
Replace BASH onboarding script with runtime-init

### ISSUE THREAD

**Issue by megamattzilla** [f5devcentral/terraform-azure-bigip-module#20]
## Replace f5_onboard.tpl Big-IP onboarding with runtime-init. 

The current Big-IP onboarding script `f5_onboard.tpl ` uses a [BASH script](https://raw.githubusercontent.com/F5Networks/f5-cloud-libs/develop/scripts/util.sh) from cloud-libs to onboard the Big-IP. 

Alternatively, F5 has created the [runtime init](https://github.com/F5Networks/f5-bigip-runtime-init) project to standardize how Big-IP VE devices are onboarded. 

Runtime init simplifies the initial DO declaration which can be submitted in YAML format. 

I believe adding runtime init to these terraform provisioner modules would help with adoption and standardization.

**Comment by nmenant** [comment]
Hi,
This is happening in our current sprint. The next release will leverage bigip-runtime-init

**Comment by megamattzilla** [comment]
Sounds great, thanks!

**Comment by nmenant** [comment]
Our next release due this week will have this addressed FYI

**Comment by papineni87** [comment]
Fixed in release v0.9.3, please reopen this issue if you see it again
