### ISSUE TITLE
support specifying "base" URL

### ISSUE THREAD

**Issue by chen23** [f5devcentral/terraform-azure-bigip-module#24]
there are customer environments where access to the public internet is restricted.  It would be helpful to allow an end-user to override the base URL of where the RPM/bigip-runtime-init are downloaded from to allow one to run in a restricted environment w/out having to override user_data

**Comment by nmenant** [comment]
https://github.com/f5devcentral/terraform-aws-bigip-module/issues/12 - this was the same thread but on the AWS module.
