### ISSUE TITLE
onboard declares DO json from hardcoded URL

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/terraform-azure-bigip-module#36]
The module references the f5_onboard.tmpl file for custom_data. Within this file, it curls a specific DO JSON file from the repo.

```
curl -o /config/cloud/do_w_admin.json -s --fail --retry 60 -m 10 -L https://raw.githubusercontent.com/f5devcentral/terraform-azure-bigip-module/master/config/onboard_do.json
```

Later on, runtime init then POSTs the declaration
```
snippet

extension_services:
  service_operations:
    - extensionType: do
      type: url
      value: file:///config/cloud/do_w_admin.json
```

The file from URL https://raw.githubusercontent.com/f5devcentral/terraform-azure-bigip-module/master/config/onboard_do.json doesn't help with onboarding and is actually confusing. When my onboard was done, I was trying to figure out what state my BIG-IP was in. I checked /var/log/cloud logs and noticed a DO declaration ran. But, the file is out of my control as it comes direct from the repo and in a sense is part of the "module" and downloads when I do terraform init.

The onboard_do.json does not match my required deployment which in this case is a 3nic.

This is the current contents of that file...some of the metadata key:value items are not even being referenced. So, I have to ask, what is the point of this file and having runtime init call it and POST the declaration?

```
{
    "schemaVersion": "1.0.0",
    "class": "Device",
    "async": true,
    "label": "my BIG-IP declaration for declarative onboarding",
    "Common": {
        "class": "Tenant",
        "hostname": "bigip1.example.com",
        "myDns": {
            "class": "DNS",
            "nameServers": [
                "169.254.169.253"
            ]
        },
        "myNtp": {
            "class": "NTP",
            "servers": [
                "0.pool.ntp.org"
            ],
            "timezone": "UTC"
        },
        "admin": {
            "class": "User",
            "userType": "regular",
            "password": "{{{ ADMIN_PASS }}}",
            "shell": "bash",
            "keys": ["{{{ SSH_KEYS }}}"]
        },
        "{{{ USER_NAME }}}": {
            "class": "User",
            "userType": "regular",
            "password": "{{{ ADMIN_PASS }}}",
            "shell": "bash",
            "keys": ["{{{ SSH_KEYS }}}"],
            "partitionAccess": {
                "all-partitions": {
                    "role": "admin"
                }
            }
        }
    }
}
```

## Workaround
After success deployment of terraform, I have a BIG-IP that installed and ran runtime-init which then posted the DO declaration. I still have to manually POST the rendered DO_3_nic file that was created by terraform (in examples folder). I can work this file into my orchestration, but I'm still curious why even bother posting the intial onboard.json file I snipped above.

**Comment by JeffGiroux** [comment]
For example, SSH_KEYS is not being referenced anywhere.

**Comment by RavinderReddyF5** [comment]
@JeffGiroux as part of runtime init integration into this module we have to use basic to DO config, to set the the user defined by module and password for same. reference examples you can find here : https://github.com/F5Networks/f5-bigip-runtime-init/blob/main/examples/config/cloud_config_local_w_do.yaml

and SSH_KEYS will be referenced from runtime parameter when we run runtime init : https://github.com/f5devcentral/terraform-azure-bigip-module/blob/master/f5_onboard.tmpl#L34

**Comment by JeffGiroux** [comment]
OK, so for example-based this repo only uses a single-nic DO declaration independent if you want a 3-nic or not. Yes, there is a DO file that is produced for 3-nic if I choose a 3-nic parameter layout, but the DO actually applied (without cloning/forking this repo and modifying) is a simple 1-nic VE DO declaration.

Suggest to put something of note in the README to make user aware that if they don't modify/clone/fork, the DO declaration as-is will not match. Also worth noting in README is that the user will have to deploy their own DO 3nic produced file afterwards.

The real fix is for user to fork or clone directory and then customize the do.json being used. I will try to fork this repo, then adjust the runtime init yaml file to use my github link address to retrieve a customized DO 3nic tempalte file. Will report back...

**Comment by papineni87** [comment]
Tracking with INFRAANO-377

**Comment by papineni87** [comment]
Updated Readme on DO declaration
