### ISSUE TITLE
ssh public key not installed to authorized_keys

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/terraform-azure-bigip-module#37]
I ran a 3nic example and tried logging into the bigip with ssh key auth but it prompted for password. I checked the .ssh/authorized_key files but the contents of the file were blank. I see in my terraform state file that the module for bigip does have the f5_ssh_publickey. But...the VM instance did NOT get the key added.

I will attempt a few more times, but this happened twice now.

My example TF...

```
module "bigip" {
  count                      = var.instanceCountBigIp
  source                     = "github.com/f5devcentral/terraform-azure-bigip-module"
  prefix                     = format("%s-bigip-%s-%s", var.projectPrefix, count.index, random_id.buildSuffix.hex)
  resource_group_name        = azurerm_resource_group.rg.name
  mgmt_subnet_ids            = [{ "subnet_id" = data.azurerm_subnet.mgmtSubnetHub.id, "public_ip" = true, "private_ip_primary" = "" }]
  mgmt_securitygroup_ids     = [module.nsg-mgmt.network_security_group_id]
  external_subnet_ids        = [{ "subnet_id" = data.azurerm_subnet.externalSubnetHub.id, "public_ip" = true, "private_ip_primary" = "", "private_ip_secondary" = "" }]
  external_securitygroup_ids = [module.nsg-external.network_security_group_id]
  internal_subnet_ids        = [{ "subnet_id" = data.azurerm_subnet.internalSubnetHub.id, "public_ip" = false, "private_ip_primary" = "" }]
  internal_securitygroup_ids = [module.nsg-internal.network_security_group_id]
  availabilityZones          = var.availabilityZones
  f5_ssh_publickey           = var.keyName
  f5_username                = var.f5UserName
}

resource "null_resource" "clusterDO" {
  count = var.instanceCountBigIp

  provisioner "local-exec" {
    command = "cat > DO_3nic-instance${count.index}.json <<EOL\n ${module.bigip[count.index].onboard_do}\nEOL"
  }
  provisioner "local-exec" {
    when    = destroy
    command = "rm -rf DO_3nic-instance${count.index}.json"
  }

  depends_on = [module.bigip.onboard_do]
}
```

**Comment by papineni87** [comment]
Thanks Jeff for raising the issue. It is fixed now in v0.9.5 release and i can use ssh keys now to login

HYD-ML-00064439:bigip_azure_3nic_deploy papineni$ ssh -i ~/.ssh/id_rsa bigipuser@40.76.140.40
The authenticity of host '40.76.140.40 (40.76.140.40)' can't be established.
ECDSA key fingerprint is SHA256:dhhc868U3rl2re78ypxw9NYVdj6G3qYgsJlG/AVbBLk.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '40.76.140.40' (ECDSA) to the list of known hosts.
[bigipuser@bigip1:Active:Standalone] ~ # 
[bigipuser@bigip1:Active:Standalone] ~ # 


Please reopen the issue if you still see it
