### ISSUE TITLE
Update Readme to remove N-nic reference

### ISSUE THREAD

**Issue by codygreen** [f5devcentral/terraform-azure-bigip-module#4]
This module only supports 1-nic, 2-nic, and 3-nic deployments.  The reference to N-nic would indicated any number of network interfaces. This is confusing module users.

**Comment by focrensh** [comment]
Tracking updates / doc changes needed with TER-454

**Comment by codygreen** [comment]
I was able to deploy a BIG-IP with 1 mgmt interface and 2 public interfaces using the code below:

```HCL
module bigip {
  source                    = "../.."
  dnsLabel                  = format("%s-%s", var.prefix, random_id.id.hex)
  resource_group_name       = azurerm_resource_group.rg.name
  mgmt_subnet_id            = [{ "subnet_id" = data.azurerm_subnet.mgmt.id, "public_ip" = true }]
  mgmt_securitygroup_id     = [module.mgmt-network-security-group.network_security_group_id]
  external_subnet_id        = [{ "subnet_id" = data.azurerm_subnet.external-public.id, "public_ip" = true }, { "subnet_id" = data.azurerm_subnet.external-public2.id, "public_ip" = true }]
  external_securitygroup_id = [module.external-network-security-group-public.network_security_group_id, module.external-network-security-group-public.network_security_group_id]
  availabilityZones         = var.availabilityZones
}
```

However, the documentation needs more details about the count dependency between `external_subnet_id` and `external_securitygroup_id`

**Comment by nmenant** [comment]
Cody,

Could you review: https://github.com/f5devcentral/terraform-azure-bigip-module/blob/master/README.md ? 

Is it providing more clarity. Does it help ?

**Comment by codygreen** [comment]
Yes, the example helps outline the mapping of the two variables.  

There are a few typo's I would recommend changing:
- consistent variable names (xxx_subnet_ids vs subnetids)
- Below example snippets show how this module called -> Below example snippets show how this module is called

Any chance we can run the readme and markdown files through a post commit hook that checks readability?

**Comment by nmenant** [comment]
thanks for the update. I'll share it with the team

**Comment by papineni87** [comment]
This is fixed now
