### ISSUE TITLE
'zones' deprecation warning

### ISSUE THREAD

**Issue by mjmenger** [f5devcentral/terraform-azure-bigip-module#42]
When using the Azure BIG-IP module, the following deprecation warning is returned for plans, applies, and destroys. 

This must be adjusted before the breaking change impacts the API.

Warning: Argument is deprecated
       │ 
       │   with module.bigip.azurerm_public_ip.mgmt_public_ip,
       │   on .terraform/modules/bigip/main.tf line 293, in resource "azurerm_public_ip" "mgmt_public_ip":
       │  293:   zones               = var.availabilityZones
       │ 
       │ This property has been deprecated in favour of `availability_zone` due to a
       │ breaking behavioural change in Azure:
       │ https://azure.microsoft.com/en-us/updates/zone-behavior-change/
       │ 
       │ (and 5 more similar warnings elsewhere)

**Comment by trinaths** [comment]
Created INFRAANO-455 for internal PM tracking.

**Comment by papineni87** [comment]
@mjmenger fixed and updated in master branch

**Comment by papineni87** [comment]
Issue is fixed in v0.9.8, please reopen the issue if you are still facing it.
