### ISSUE TITLE
secondary IP address needed for application - virtual server listener

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/terraform-azure-bigip-module#5]
The base orchestration does NOT allocate at least one secondary IP to the external NIC. This is needed for VIP traffic in most common scenarios. Yes, users can target a self IP for the virtual server listener, but this is not always recommended.

Suggesting to add a secondary IP configuration to the external NIC of each F5. This is similar to what happens in the ARM templates in which the external nic gets assigned a primary IP (self IP) as well as one additional secondary IP (virtual listener, SNAT, whatever).

If this is not done during terraform apply, then it will be up to the user to manually create a new IP object in the cloud provider, then bind it to the newly deployed VM.

**Comment by focrensh** [comment]
Thanks, tracking with TER-452

**Comment by papineni87** [comment]
This is fixed now
