### ISSUE TITLE
custom_user_data as required field is a breaking change

### ISSUE THREAD

**Issue by mjmenger** [f5devcentral/terraform-azure-bigip-module#50]
when switching to 0.9.8, the custom_user_data attribute is listed as required and breaks builds that do not require custom_user_data.

Steps to reproduce:

select a Terraform project that works with a previous version of the AWS BIG-IP module
change module source reference from a previous version to 0.9.8
run Terraform apply
Expected Result:

creates the same result when using previous module versions
Actual Result:

error message indicating that custom_user_data is a required attribute

**Comment by papineni87** [comment]
Issue is fixed in v0.9.9, Please reopen the issue if it still persists

**Comment by mjmenger** [comment]
0.9.9 passed all of my tests 👍
