### ISSUE TITLE
Docs: specify required Terraform Provider Module Versions

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/terraform-azure-bigip-module#6]
It would be nice to know the minimum required terraform version for this repo to make it work. It's also nice to know the minimum Azure resource provider version as well as the module versions. I had a repo in which i pinned my Azurerm provider to 2.1. However, running this terraform-azure-bigip-module with the Azurerm provider 2.1 will cause failures for the 'address_prefix' when assigning subnets. This appears to be non-existent in the latest Azurerm provider v2.25.0.

Hence, suggesting that you place minimum required versions on the README. Something like this...
```
This template is tested and worked in the following version
Terraform v0.12.29
+ provider.azurerm v2.25.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2
```

For reference, I hit this Azurerm bug - https://github.com/Azure/terraform-azurerm-network/issues/41. Once I allowed version for Azurerm to be newer, the terraform-azure-bigip-module worked fine. It did NOT work with Azurerm 2.1 but it does work with Azurerm 2.25.

My example version pinning...
```
# Terraform Version Pinning
terraform {
  required_version = "~> 0.12"
  required_providers {
    azurerm = "~> 2"
  }
}
```

**Comment by focrensh** [comment]
Tracking with TER-455

**Comment by JeffGiroux** [comment]
Looks good as long as the versions pinned are updated/tested periodically to allow newer versions of the provider module. For example, if AzureRM releases 2.29 then the current pin lock of 2.28 will not get it. Just an example. Otherwise this is fine as the docs clearly state the version tested, and the repo pins the version so as to keep the examples and code "in tact" when people consume it for their own purposes. It's then up to user to validate required items in their environment, and if a new provider update is needed...then the user can update the pinning and provide feedback to this repo via github issue.

Thx, Jeff

**Comment by papineni87** [comment]
Closing the issue with the changes in doc, and addition of terraform block with specific versions.
